### ISSUE TITLE
Bump dependency on miniquad to latest alpha

### ISSUE THREAD

**Issue by jackfranklin** [not-fl3/egui-miniquad#34]
I'm currently unable to install egui-macroquad with the latest macroquad because of a difference in their miniquad-alpha dependencies (see https://github.com/optozorax/egui-macroquad/issues/16)

egui-miniquad depends on miniquad-alpha 43, whereas macroquad depends on miniquad-alpha 45.

I'm happy to submit a PR to update the dependency in this repo; if so would you be happy to merge and release a new version? Thanks!

**Comment by Zageron** [comment]
@not-fl3 :)?

**Comment by emilk** [comment]
@jackfranklin just make a PR and I'll merge it for you!
