### ISSUE TITLE
Unable to run test_window example

### ISSUE THREAD

**Issue by Ace4896** [not-fl3/egui-miniquad#4]
Hi, I've been looking into egui and wanted to try out miniquad for rendering. I was trying to update this to work with the latest miniquad and egui versions, but the app crashes immediately with:

```
error: process didn't exit successfully: `target\debug\examples\test_window.exe` (exit code: 0xc0000005, STATUS_ACCESS_VIOLATION)
```

I'm seeing this error with the versions used by the current master branch as well, so I'm not sure where the error is coming from.

I'm on Windows 10 2004 with Rust 1.47.0. If it helps, I've tried out the miniquad examples from the main repo, and they work fine.

**Comment by emilk** [comment]
Can you try running the debug build with `RUST_BACKTRACE=1` ?

**Comment by Ace4896** [comment]
Ah, I made this issue a long time ago - I just tried out the new example app, and I'm able to get it to run this time. However, I'm getting some corrupted output on the current master (c2bb39e0ab1cecb31241ad7bd7789ab49aed9f71):

![image](https://user-images.githubusercontent.com/31632386/112467494-062db380-8d5f-11eb-9ecc-069fa55649b2.png)

I forgot to mention this last time, but I'm using a laptop with a GTX 1050; the driver version is 461.92.

FWIW, the egui examples in the main repo and the miniquad examples work just fine - hope that helps narrow down the issue.

**Comment by emilk** [comment]
Oh well, at least it is better than crashing :) Thanks for trying this again!

Very weird though. Maybe @not-fl3 has some idea.

**Comment by not-fl3** [comment]
Works on my machine :/ 

I saw a similar(?) miniquad bug report from windows/nvidia before and somehow they solved it by driver manipulation. 
But can't say much unfortunately, will try to somehow reproduce it, but I do not have good ideas how to reproduce it yet :(

**Comment by Tropid** [comment]
I have the same problem. I tried a lot of older revisions and it happened on every single one I tested. I also have an Nvidia graphics card. The strange thing is if I debug the rendering with RenderDoc (https://renderdoc.org/) the output looks fine.

Windows window:
![image](https://user-images.githubusercontent.com/923818/118399657-76b9c800-b65e-11eb-93b7-f99fa19b91ce.png)

RenderDoc:
![image](https://user-images.githubusercontent.com/923818/118399669-85a07a80-b65e-11eb-915a-0d31adeb5d14.png)

**Comment by Ace4896** [comment]
Hey @not-fl3, I noticed that you've recently pushed a fix for the flickering issue on Windows + NVIDIA - just letting you know that everything is working fine now!

![image](https://user-images.githubusercontent.com/31632386/121669782-977e0d80-caa4-11eb-9a31-69572c5367a2.png)
