### ISSUE TITLE
rename respository to `egui-miniquad`

### ISSUE THREAD

**Issue by emilk** [not-fl3/egui-miniquad#9]
I renamed `Emigui` to `egui` last year. Sorry for that :)

It would be nice to get the new name in though so we can publish this crate as `egui-miniquad`.

Thankfully, it is easy to rename a repo in GitHub (it even keeps redirecting): https://docs.github.com/en/github/administering-a-repository/renaming-a-repository

**Comment by not-fl3** [comment]
Done! :)
